[package]
name = "crazyflie-lib"
version = "0.1.0"
authors = ["Arnaud Taffanel <arnaud@bitcraze.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crazyflie-link = { version = "*", path = "../crazyflie-link-rs/crazyflie-link", default-features = false }
async_executors = "0.4.1"
futures-util = "0.3.14"
futures = "0.3.14"
async-stream = "0.3.1"
flume = "0.10.5"
async-trait = "0.1.50"
num_enum = "0.5.1"
half = "1.7.1"

async-std = { version = "1.9.0", features = ["attributes"], optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }

[features]
default = ["async-std", "crazyflie-link/native"]
web = ["wasm-bindgen-futures", "crazyflie-link/webusb"]