[package]
name = "crazyflie-lib"
version = "0.1.0"
authors = ["Arnaud Taffanel <arnaud@bitcraze.io>"]
edition = "2018"

[dependencies]
crazyflie-link = { version="0.2.0", default-features = false }
async_executors = { version="0.4.2", features=["timer"] }
futures-util = "0.3"
futures = "0.3"
async-stream = "0.3.1"
flume = "0.10.5"
async-trait = "0.1.50"
num_enum = "0.5.1"
half = "1.7.1"

async-std = { version = "1.9.0", features = ["attributes"], optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }

[dev-dependencies]
env_logger = "0.8"
async_executors = { version="0.4.2", features=["async_std"] }

[features]
default = ["async-std", "crazyflie-link/native"]
web = ["wasm-bindgen-futures", "crazyflie-link/webusb"]
